services:
  database:
    image: postgres:latest
    environment:
      POSTGRES_USER: rafi
      POSTGRES_PASSWORD: rafi123
      POSTGRES_DB: express-management
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build: .
    environment:
      DATABASE_URL: "postgresql://rafi:rafi123@database:5432/express-management"
    ports:
      - "3001:3000"
    depends_on:
      - database
    
  prisma:
    image: node:16
    working_dir: /app
    volumes:
      - .:/app
    command: ["npx", "prisma", "studio"]
    ports:
      - "5555:5555"
    depends_on:
      - database

volumes:
  postgres_data: